# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f840bd74de4d3c09e1566ddfb425b991e629719d91e9ee232ab8decae9b7573442d188ecf097278b25adc7f97e90a661e3289369ab8ab5ecc827b6ce4578ba66

test:
  secret_key_base: e6822ce33e22ced4dac1dec39cecc121d191609e9d37fb7cbbfe99e638c8cb85fd6ac3416bb4320115e2c67bf3be13899fb7529b742fdb23566f82dfb2410db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
